### QUESTION 1

Given a raw data of the record of the attendance for 15 employees in a company for a 14 days event. The exported raw data is recorded in following way:

<br>
<img src="Figure1.png", style="width: 300px";>

#### Question 1(a)
Read the “Attendance_RAW.txt” and save the data into a NumPy array

In [1]:
# WRITE YOUR CODE HERE

import numpy as np
  
data = np.loadtxt("Attendance_RAW.txt", dtype=int)
data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1])

#### Question 1(b)
Shape the NumPy array to a structure where row represents the employees, column represents the working days. (Hint: reshape the data and then swapaxes/transpose)

Expected Output:

<br>
<img src="Figure2.png", style="width: 200px";>

In [2]:
# WRITE YOUR CODE HERE

arr1 = data.reshape((14,15))
arr1
arr2= arr1.T
arr2


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
       [1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1]])

#### Question 1(c)
Construct a function that can calculate and return the list of average of attendance for each day

In [3]:
# WRITE YOUR CODE HERE

def AvgAttendance(arr2):
    return np.average(arr2, axis=0) 

print(AvgAttendance(arr2).tolist())


[0.9333333333333333, 0.9333333333333333, 0.6666666666666666, 0.6666666666666666, 0.7333333333333333, 0.7333333333333333, 0.7333333333333333, 0.6, 0.7333333333333333, 0.6666666666666666, 1.0, 0.6666666666666666, 0.8, 0.6666666666666666]


### QUESTION 2
Given a data file, “emp_detail.csv” which consists of the employee’s details: name and department

#### Question 2(a)
Using Pandas library, read the CSV data file in Python into a variable named `emp_detail`

In [4]:
# WRITE YOUR CODE HERE

import pandas as pd 

emp_detail = pd.read_csv("emp_detail.csv")
emp_detail


Name Department
0       ALI    FINANCE
1     AHMAD   STAFFING
2     CHONG    FINANCE
3    DARREN   STAFFING
4   JASMINE   STAFFING
5    JOSHUA   STAFFING
6     KELLY    FINANCE
7       LIM    FINANCE
8   NATASHA    FINANCE
9      OMAR   STAFFING
10   PATRIC   STAFFING
11     ROSE   STAFFING
12    SATYA   STAFFING
13    TARIQ   STAFFING
14    USMAN   STAFFING

#### Question 2(b) 
Display the first five rows of records

In [5]:
# WRITE YOUR CODE HERE

emp_detail.head()

Name Department
0      ALI    FINANCE
1    AHMAD   STAFFING
2    CHONG    FINANCE
3   DARREN   STAFFING
4  JASMINE   STAFFING

#### Question 2(c)
Using the NumPy object of the attendance record created earlier in Question 1, convert the NumPy object into Data Frame, name it `attendance`

In [6]:
# WRITE YOUR CODE HERE

import pandas as pd

attendance = pd.DataFrame(arr2)
attendance

0   1   2   3   4   5   6   7   8   9   10  11  12  13
0    1   1   1   1   1   1   1   1   1   1   1   1   1   1
1    1   1   1   0   1   1   1   1   1   1   1   1   1   1
2    1   1   1   1   1   1   0   1   0   0   1   0   0   0
3    1   1   1   1   1   0   1   0   1   1   1   1   0   1
4    1   1   0   1   0   1   1   0   1   0   1   1   1   1
5    1   1   1   1   0   1   0   1   1   0   1   0   1   1
6    1   1   0   0   0   1   1   0   0   0   1   0   1   0
7    1   1   0   1   0   0   1   0   1   0   1   0   1   0
8    1   1   1   1   1   1   0   1   0   1   1   0   1   0
9    1   0   1   1   1   1   0   1   1   1   1   1   1   1
10   1   1   0   1   1   1   1   1   0   1   1   1   1   0
11   1   1   1   1   1   1   1   1   1   1   1   1   1   1
12   1   1   1   0   1   0   1   0   1   1   1   1   1   1
13   1   1   0   0   1   0   1   1   1   1   1   1   1   1
14   0   1   1   0   1   1   1   0   1   1   1   1   0   1

#### Question 2(d)
Merge the Data Frames `emp_detail` and `attendance` into a new data frame, name it `emp_attendance`

In [7]:
# WRITE YOUR CODE HERE

emp_attendance =pd.concat([emp_detail, attendance],axis = 1)
emp_attendance

Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1
1     AHMAD   STAFFING  1  1  1  0  1  1  1  1  1  1   1   1   1   1
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   0   0   0
3    DARREN   STAFFING  1  1  1  1  1  0  1  0  1  1   1   1   0   1
4   JASMINE   STAFFING  1  1  0  1  0  1  1  0  1  0   1   1   1   1
5    JOSHUA   STAFFING  1  1  1  1  0  1  0  1  1  0   1   0   1   1
6     KELLY    FINANCE  1  1  0  0  0  1  1  0  0  0   1   0   1   0
7       LIM    FINANCE  1  1  0  1  0  0  1  0  1  0   1   0   1   0
8   NATASHA    FINANCE  1  1  1  1  1  1  0  1  0  1   1   0   1   0
9      OMAR   STAFFING  1  0  1  1  1  1  0  1  1  1   1   1   1   1
10   PATRIC   STAFFING  1  1  0  1  1  1  1  1  0  1   1   1   1   0
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   1
12    SATYA   STAFFING  1  1  1  0  1  0  1  0  1  1   1   1   1   1
13    TARIQ   STAFFING  1  1  0  0  1  0  1  1  1  1   1   1   1   1
14    USMAN   STAFFING  0  1  1  0  1  1  1  0  1  1   1   1   0   1

#### Question 2(e)
Add a column with name `total` into the `emp_attendance` Data Frame that consists of the total number of days the employee attended the event

In [8]:
# WRITE YOUR CODE HERE

emp_attendance['total'] = emp_attendance.loc[:,0:13].sum(axis=1)
emp_attendance

Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13  total
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14
1     AHMAD   STAFFING  1  1  1  0  1  1  1  1  1  1   1   1   1   1     13
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   0   0   0      8
3    DARREN   STAFFING  1  1  1  1  1  0  1  0  1  1   1   1   0   1     11
4   JASMINE   STAFFING  1  1  0  1  0  1  1  0  1  0   1   1   1   1     10
5    JOSHUA   STAFFING  1  1  1  1  0  1  0  1  1  0   1   0   1   1     10
6     KELLY    FINANCE  1  1  0  0  0  1  1  0  0  0   1   0   1   0      6
7       LIM    FINANCE  1  1  0  1  0  0  1  0  1  0   1   0   1   0      7
8   NATASHA    FINANCE  1  1  1  1  1  1  0  1  0  1   1   0   1   0     10
9      OMAR   STAFFING  1  0  1  1  1  1  0  1  1  1   1   1   1   1     12
10   PATRIC   STAFFING  1  1  0  1  1  1  1  1  0  1   1   1   1   0     11
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14
12    SATYA   STAFFING  1  1  1  0  1  0  1  0  1  1   1   1   1   1     11
13    TARIQ   STAFFING  1  1  0  0  1  0  1  1  1  1   1   1   1   1     11
14    USMAN   STAFFING  0  1  1  0  1  1  1  0  1  1   1   1   0   1     10

#### Question 2(f)
Add a column with name `rate` into the `emp_attendance` Data Frame that consists of the attendance rate / percentage the employee throughout the 14 days

In [9]:
# WRITE YOUR CODE HERE

emp_attendance['rate'] = (emp_attendance.total/14)*100
emp_attendance


Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13  total  \
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14   
1     AHMAD   STAFFING  1  1  1  0  1  1  1  1  1  1   1   1   1   1     13   
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   0   0   0      8   
3    DARREN   STAFFING  1  1  1  1  1  0  1  0  1  1   1   1   0   1     11   
4   JASMINE   STAFFING  1  1  0  1  0  1  1  0  1  0   1   1   1   1     10   
5    JOSHUA   STAFFING  1  1  1  1  0  1  0  1  1  0   1   0   1   1     10   
6     KELLY    FINANCE  1  1  0  0  0  1  1  0  0  0   1   0   1   0      6   
7       LIM    FINANCE  1  1  0  1  0  0  1  0  1  0   1   0   1   0      7   
8   NATASHA    FINANCE  1  1  1  1  1  1  0  1  0  1   1   0   1   0     10   
9      OMAR   STAFFING  1  0  1  1  1  1  0  1  1  1   1   1   1   1     12   
10   PATRIC   STAFFING  1  1  0  1  1  1  1  1  0  1   1   1   1   0     11   
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14   
12    SATYA   STAFFING  1  1  1  0  1  0  1  0  1  1   1   1   1   1     11   
13    TARIQ   STAFFING  1  1  0  0  1  0  1  1  1  1   1   1   1   1     11   
14    USMAN   STAFFING  0  1  1  0  1  1  1  0  1  1   1   1   0   1     10   

          rate  
0   100.000000  
1    92.857143  
2    57.142857  
3    78.571429  
4    71.428571  
5    71.428571  
6    42.857143  
7    50.000000  
8    71.428571  
9    85.714286  
10   78.571429  
11  100.000000  
12   78.571429  
13   78.571429  
14   71.428571

#### Question 2(g)
Consider following rules in classify the attendance:

    Rate > 90% : Good
    60% < Rate < 90% : Moderate
    Rate < 60% : Bad

Based on the grouping rule above, get the status for each of the staff and save the status in a new column `status` in the Data Frame


In [10]:
# WRITE YOUR CODE HERE

def status(rate):
    
    if rate >90:
        status= 'Good'
    elif rate <60:
        status= 'Bad'
    else:
        status= 'Moderate'
    return status
    

emp_attendance['status'] = emp_attendance['rate'].apply(status)
emp_attendance


Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13  total  \
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14   
1     AHMAD   STAFFING  1  1  1  0  1  1  1  1  1  1   1   1   1   1     13   
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   0   0   0      8   
3    DARREN   STAFFING  1  1  1  1  1  0  1  0  1  1   1   1   0   1     11   
4   JASMINE   STAFFING  1  1  0  1  0  1  1  0  1  0   1   1   1   1     10   
5    JOSHUA   STAFFING  1  1  1  1  0  1  0  1  1  0   1   0   1   1     10   
6     KELLY    FINANCE  1  1  0  0  0  1  1  0  0  0   1   0   1   0      6   
7       LIM    FINANCE  1  1  0  1  0  0  1  0  1  0   1   0   1   0      7   
8   NATASHA    FINANCE  1  1  1  1  1  1  0  1  0  1   1   0   1   0     10   
9      OMAR   STAFFING  1  0  1  1  1  1  0  1  1  1   1   1   1   1     12   
10   PATRIC   STAFFING  1  1  0  1  1  1  1  1  0  1   1   1   1   0     11   
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14   
12    SATYA   STAFFING  1  1  1  0  1  0  1  0  1  1   1   1   1   1     11   
13    TARIQ   STAFFING  1  1  0  0  1  0  1  1  1  1   1   1   1   1     11   
14    USMAN   STAFFING  0  1  1  0  1  1  1  0  1  1   1   1   0   1     10   

          rate    status  
0   100.000000      Good  
1    92.857143      Good  
2    57.142857       Bad  
3    78.571429  Moderate  
4    71.428571  Moderate  
5    71.428571  Moderate  
6    42.857143       Bad  
7    50.000000       Bad  
8    71.428571  Moderate  
9    85.714286  Moderate  
10   78.571429  Moderate  
11  100.000000      Good  
12   78.571429  Moderate  
13   78.571429  Moderate  
14   71.428571  Moderate

The output after you have performed question 2(d) - 2(g) should look like below:

<br>
<img src="Figure3.png", style="width: 500px";>



#### Question 2(h)
Construct a function that returns the average attendance of all staff over the 14 days according to the department

In [11]:
# WRITE YOUR CODE HERE

# WRITE YOUR CODE HERE

def department_average_attendance(emp_attendance):
    return emp_attendance.groupby(['Department'],as_index=False).total.mean()

print(department_average_attendance(emp_attendance))

  Department  total
0    FINANCE    9.0
1   STAFFING   11.3


## Question 3

#### Question 3(a)

Create a NumPy array like below:

    array([[33, 22, 11],
           [55, 66, 44],
           [99, 88, 77]])

In [12]:
# WRITE YOUR CODE HERE

import numpy as np

arr3 = np.array([[33, 22, 11], [55, 66, 44],[99,88,77]])
arr3

array([[33, 22, 11],
       [55, 66, 44],
       [99, 88, 77]])

#### Question 3(b)
Sort the array given in ascending order

In [13]:
# WRITE YOUR CODE HERE

arr3_sort=np.sort(arr3)
arr3_sort

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

#### Question 3(c)
Compute sum of all elements, sum of each column and sum of each row of the sorted array

In [14]:
# WRITE YOUR CODE HERE

sum_all= arr3_sort.sum()

sum_col= np.sum(arr3_sort, axis=0) 

sum_row= np.sum(arr3_sort, axis=1) 

print("Sum of all elements:", sum_all)
print("Sum of each column:", sum_col)
print("Sum of each row:", sum_row)

Sum of all elements: 495
Sum of each column: [132 165 198]
Sum of each row: [ 66 165 264]


#### Question 3(d)
Compute mean of all elements, mean of each column and mean of each row of the sorted array

In [15]:
# WRITE YOUR CODE HERE

mean_all= np.average(arr3_sort)

mean_col= np.average(arr3_sort, axis=0)

mean_row = np.average(arr3_sort, axis=1)

print("Mean of all elements:", mean_all)
print("Mean of each column:", mean_col)
print("Mean of each row:", mean_row)


Mean of all elements: 55.0
Mean of each column: [44. 55. 66.]
Mean of each row: [22. 55. 88.]


#### Compute 3(e)
Compute cumulative sum of each column and cumulative product of each row of the given array

In [16]:
# WRITE YOUR CODE HERE
cumulative_sum= np.cumsum(arr3, axis=0)

cumulative_product= np.cumprod(arr3,axis=1)

print("Cumulative sum of each column:")
print(cumulative_sum)

print()

print("Cumulative product of each row:")
print(cumulative_product)

Cumulative sum of each column:
[[ 33  22  11]
 [ 88  88  55]
 [187 176 132]]

Cumulative product of each row:
[[    33    726   7986]
 [    55   3630 159720]
 [    99   8712 670824]]


## Question 4
For this question, you are using Automobile Dataset.


#### Question 4(a)
Load the dataset into pandas dataframe

In [17]:
# WRITE YOUR CODE HERE

df= pd.read_csv("Automobile Dataset.csv")

#### Question 4(b)
Display the first and last 5 rows

In [18]:
# WRITE YOUR CODE HERE

print("First 5 rows:")
print(df.head())

print()

print("Last 5 rows:")
print(df.tail())


First 5 rows:
   index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0  

Last 5 rows:
    index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         

#### Question 4(c)
Print most expensive car’s company name and price

In [19]:
# WRITE YOUR CODE HERE

expensive_car= df [['company','price']][df.price==df['price'].max()]

print("Most expensive car’s company name and price;")
print()
print(expensive_car)

Most expensive car’s company name and price;

          company    price
35  mercedes-benz  45400.0


#### Question 4(d)
Count total cars per company

In [20]:
# WRITE YOUR CODE HERE

df['company'].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: company, dtype: int64

#### Question 4(e)
Select only Toyota's cars. Find the average mileage and price of Toyota's cars

In [21]:
toyota= df.loc[df['company'] == 'toyota']
average_price = '{:.2f}'.format(toyota['price'].mean())
average_mileage = toyota['average-mileage'].mean()

print("Average Price of Toyota's cars:", average_price)
print("Average Mileage of Toyota's cars:", average_mileage)


Average Price of Toyota's cars: 8216.86
Average Mileage of Toyota's cars: 28.714285714285715


#### Question 4(f)
Sort all cars by Price and Horsepower column. List the expensive cars first

In [22]:
# WRITE YOUR CODE HERE

cars_sort = df.sort_values(by=['price', 'horsepower'], ascending=False)
cars_sort

index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   
..    ...            ...          ...         ...     ...         ...   
27     36          mazda    hatchback        93.1   159.1         ohc   
13     16      chevrolet    hatchback        88.4   141.1           l   
47     63        porsche    hatchback        98.4   175.7       dohcv   
22     31          isuzu        sedan        94.5   155.9         ohc   
23     32          isuzu        sedan        94.5   155.9         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0  
11              six         182               16  41315.0  
34            eight         184               14  40960.0  
46              six         207               17  37028.0  
12              six         182               15  36880.0  
..              ...         ...              ...      ...  
27             four          68               30   5195.0  
13            three          48               47   5151.0  
47            eight         288               17      NaN  
22             four          70               38      NaN  
23             four          70               38      NaN  

[61 rows x 10 columns]

#### Question 4(g)
Display all the maximum car price for each company

In [23]:
# WRITE YOUR CODE HERE

car_company = df.groupby('company')
max_car_price= car_company['price'].max()
max_car_price


company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64